# Numpy
- 'Num'erical 'Py'thon
- 파이썬에서 수치 연산을 수행하는 라이브러리
- 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 데이터 분석을 할 때 사용되는 라이브러리인 pandas와 matplotlib의 기반으로 사용
- 기본적으로 array(배열) 단위로 데이터를 관리하며 이에 대해 연산을 수행함

In [1]:
#!pip install numpy

In [2]:
import numpy as np

## ndarray (n차원 배열)
- Numpy의 n차원 배열 객체
- 파이썬의 리스트와 다르게 1개의 data type만 넣을 수 있음
- ndarray의 데이터는 zero-based index로 접근 가능
- rank: 배열의 차원(dimension)
- shape: 각 차원의 크기를 튜플로 표시하는 것

## 1. array 기본

### 1-1. ndarray 생성
- 파이썬 리스트, 튜플에 대해 np.array()를 사용해 배열 생성

In [3]:
list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [4]:
list2 = [1, 2, 3.5, 4, 5]
list2

[1, 2, 3.5, 4, 5]

In [5]:
# 파이썬 list, tuple에 대해 np.array() 함수를 이용하여 배열 생성 가능
array1 = np.array(list1)
array1

array([1, 2, 3, 4, 5])

In [6]:
type(array1)

numpy.ndarray

In [7]:
array2 = np.array([1, 2, 3.5, 4, 5])
#[1, 2, 3.5, 4, 5]가 왜 [1. , 2. , 3.5, 4. , 5. ]로 바뀌었을까? -> dtype이 1개
array2

array([1. , 2. , 3.5, 4. , 5. ])

In [ ]:
# n차원 배열
# 리스트(튜플)안에 리스트(튜플)안에 리스트(튜플)안에.... 리스트(튜플) ==차원이 높아진다
array3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
array3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
# array4를 직접 만들어보자!
#---------------------------------------------------------------
array4 = np.array([[1.5, 2, 2.5],[3, 3.5, 4], [4.5, 5, 5.5]])
#---------------------------------------------------------------
array4

array([[1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [ ]:
list5 = [[[1,2],[3,4],[5,6]],[[5,6],[7,8],[9,10]]]
list5

[[[1, 2], [3, 4], [5, 6]], [[5, 6], [7, 8], [9, 10]]]

In [ ]:
array5 = np.array(list5)
array5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

### 1-2. ndarray의 차수, 모양, 자료 타입 확인

|함수|설명|
|--|--|
|ndarray.shape|배열이 몇 행 몇 열인지|
|ndarray.ndim|배열의 차원 수|
|ndarray.size|배열의 전체 원소의 개수|
|ndarray.dtype|배열의 자료 타입|

In [ ]:
array1

array([1, 2, 3, 4, 5])

In [ ]:
array3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
array5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

#### 1) shape

In [ ]:
# .shape를 통해 ndarray가 몇 행 몇 열인지 알 수 있음
array1.shape
#(5,)와 (1,5)의 차이점은? (5,)는 1차원, (1,5)는 2차원

(5,)

In [ ]:
array3.shape

(4, 3)

In [ ]:
array5.shape

(2, 3, 2)

#### 2) ndim

In [ ]:
# .ndim을 통해 몇 차원인지 알 수 있음
array5.ndim

3

#### 3) size

In [ ]:
# .size를 통해 전체 원소의 개수를 알 수 있음
array5.size
# 2*3*2 = 12

12

#### 4) dtype

In [ ]:
# .dtype를 통해 자료 타입을 알 수 있음
# ndarray는 같은 타입의 데이터만을 가질 수 있음
array1.dtype

dtype('int64')

##### ndarray 자료형

- Numpy는 Python보다 더 다양한 자료형을 지원
- 아래 중 가장 많이 쓰는 자료형: int32, int64, float32, complex128, bool
- Numpy는 기본적으로 input에서 자동적으로 자료형을 설정하지만, *dtype* argument를 통해 array 생성 시 자료형을 설정 가능
- (자료형 뒤에 붙는 숫자는 bit의 개수를 의미)

|dtype|설명|
|------|---|
|int8, int16, int32, int64|정수|
|uint8, uint16, uint32, uint64|부호가 없는 정수|
|float16, float32, float64, float128|실수|
|complex64, complex128, complex256|복소수|
|bool|불리언|
|string|문자열|
|object|객체|
|unicode|유니코드|

In [ ]:
# 자료 타입을 지정해서 array를 생성할 수 있음
array6 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]], dtype="float")
print(array6)
print(array6.dtype)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64


#### 5) 연습

In [ ]:
array3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
print(array3.shape)
print(array3.ndim)
print(array3.size)
print(array3.dtype)

(4, 3)
2
12
int64


In [9]:
array4

array([[1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [ ]:
# array4의 모양, 차원, 원소 개수, 자료 타입을 print 해보자!
print()
print()
print()
print()

(3, 3)
2
9
float64


### 1-3. ndarray의 타입 변환

In [ ]:
# astype()을 통해 자료 타입 변환 가능
array7 = array6.astype(int)
array7

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# astype() 적용 시 dtype이 변환된 새로운 ndarray가 생성되어 기존의 ndarray는 변화가 없음
array6

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

### 1-4. 특정 ndarray 생성 함수

|함수|설명|
|------|---|
|zeros(shape)|입력 받는 shape만큼 모든 값이 0인 초기화된 배열 생성|
|ones(shape)|입력 받는 shape만큼 모든 값이 1인 초기화된 배열 생성|
|empty(shape)|초기화되지 않은 배열 생성|
|arange(start,end,shape)|숫자 범위 및 간격에 따른 배열 생성|

#### 1) zeros

In [ ]:
# zeros(shape): 입력받는 형태만큼 모든 값이 0인 배열을 생성함
# dtype default는 float64
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 2) ones

In [ ]:
# ones(shape): 입력받는 형태만큼 모든 값이 1인 배열을 생성함
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 3) empty

In [ ]:
# empty(shape): 초기화되지 않은 값으로 zeros나 ones와 마찬가지로 배열을 생성
np.empty((3,3))

array([[1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

#### 4) arange

In [ ]:
# arange(start,end,step): 원하는 숫자 범위 및 간격(step)에 따른 array를 생성
# start는 포함, end는 미포함
# 1개의 숫자(end) 입력 시 0부터 end-1까지 1씩 증가하는 배열 생성
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 2개의 숫자(start, end) 입력 시 start부터 end-1까지 1씩 증가하는 배열 생성
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 3번째 자리에 간격을 설정
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

### 1-5. array의 재배열

#### 1) reshape

In [ ]:
array = np.arange(8)
array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# reshape(): array의 데이터를 바꾸지 않고 shape을 변환
# 기존의 array는 reshape된 array와 size가 동일해야 함
# 기존의 array를 변환하지 못하기 때문에 새로운 array에 할당
array_reshaped = array.reshape(2, 4)
array_reshaped

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### 2) reshape() 안에 '-1'이 들어가 있는 경우
- 변경된 배열의 '-1' 위치의 차원은 원래 배열의 size와 남은 차원으로부터 추정

In [ ]:
# reshape(정수,-1): 열 위치에 '-1'이 들어있을 경우
array_reshaped2 = array.reshape(4, -1)
array_reshaped2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
# reshape(-1,정수): 행 위치에 '-1'이 들어있을 경우
array_reshaped3 = array.reshape(-1,2)
array_reshaped3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
# reshape(-1): reshape(1,-1)과 같이 1차원 배열을 반환
array_reshaped4 = array.reshape(-1)
array_reshaped4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
array5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

In [ ]:
array5_reshaped = array5.reshape(2,2,-1)
array5_reshaped
# '-1'은 1개의 차원에 한해서만 설정 가능
# array5.reshape(2,-1,-1) -> error

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [ ]:
#아래와 같은 array를 만들어 보자! (빈 칸 채우기)
array=np.arange()
array_reshaped=array.reshape()
array_reshaped

array([[[80, 77],
        [74, 71],
        [68, 65],
        [62, 59]],

       [[56, 53],
        [50, 47],
        [44, 41],
        [38, 35]]])

---

## 2. Array 연산

- 원칙적으로 ndarray의 shape가 같아야 연산 가능.
- 각 array의 같은 자리에 있는 요소들끼리(element-wise) 연산하기 때문. (그렇지 않을 경우 브로드캐스팅)

In [ ]:
print(list1)
print(list2)

[1, 2, 3, 4, 5]
[1, 2, 3.5, 4, 5]


In [ ]:
list1*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
array1*2

array([ 2,  4,  6,  8, 10])

In [ ]:
array8 = np.array([[1,2,3],[4,5,6]])
array8

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array9 = np.array([[10,11,12],[13,14,15]])
array9

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
print(array8.shape)
print(array9.shape)

(2, 3)
(2, 3)


### 2-1. 사칙연산
- operator 또는 ufunc으로 연산 가능

#### 1) 덧셈

In [ ]:
array8 + array9

array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
np.add(array8 ,array9)

array([[11, 13, 15],
       [17, 19, 21]])

#### 2) 뺄셈

In [ ]:
array8 - array9

array([[-9, -9, -9],
       [-9, -9, -9]])

In [ ]:
np.subtract(array8, array9)

array([[-9, -9, -9],
       [-9, -9, -9]])

#### 3) 곱셈

In [ ]:
array8 * array9

array([[10, 22, 36],
       [52, 70, 90]])

In [ ]:
np.multiply(array8, array9)

array([[10, 22, 36],
       [52, 70, 90]])

#### 4) 나눗셈

In [ ]:
array8 / array9

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [ ]:
np.divide(array8, array9)

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

### 2-2. np.dot(): 벡터 내적, 행렬 곱

#### 1) 벡터 내적: 1차원 x 1차원

In [ ]:
# 1차원 x 1차원 (array의 원소 개수가 일치해야 함)
# element-wise 방식으로 벡터 내적
a = np.arange(1, 11)
b = np.arange(11, 21)

In [ ]:
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [ ]:
print(a * b)
print(np.dot(a,b))

[ 11  24  39  56  75  96 119 144 171 200]
935


#### 2) 행렬 곱: 2차원 x 2차원
- (2, 3) * (3, 4) -> 가능
- (2, 3) * (2, 3) -> 불가능

In [ ]:
# 2차원 x 2차원
# 행렬 곱
a = np.array([[1, 3, 5], [2, 4, 6]])
b = np.array([[1, 6], [3, 0], [5, 2]])

print(a.shape)
print(b.shape)

(2, 3)
(3, 2)


In [ ]:
print(a)
print(b)

[[1 3 5]
 [2 4 6]]
[[1 6]
 [3 0]
 [5 2]]


In [ ]:
#(2,2)가 나온다
np.dot(a, b)

array([[35, 16],
       [44, 24]])

### 2-3. 평균, 최댓값, 최솟값

<br>

#### numpy의 array에 적용되는 통계 함수

|함수|설명|
|--|---|
|sum|전체 원소의 합 계산|
|mean|전체 원소의 평균 계산|
|std, var|전체 원소의 표준편차, 분산 계산|
|min, max|전체 원소의 최솟값, 최댓값 계산|
|argmin, argmax|전체 원소의 최솟값, 최댓값이 위치한 인덱스를 반환|
|cumsum|첫번째 원소부터 각 원소까지의 누적합 계산 (0부터 더해짐)|
|cumprod|첫번째 원소부터 각 원소까지의 누적곱 계산 (1부터 곱해짐)|



In [ ]:
array8

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 1개 array의 전체 원소의 평균 계산
np.mean(array8)

3.5

In [ ]:
# 1개 array의 전체 원소의 최솟값, 최댓값 계산
print(np.min(array8))
print(np.max(array8))

1
6


In [ ]:
# 2개 array에서 동일한 위치의 원소끼리 비교하여 둘 중 최솟값, 최댓값을 반환
print(np.minimum(array8, array9))
print(np.maximum(array8, array9))

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


### 2-4. 브로드캐스팅

- 원칙적으로 shape가 같아야 연산 가능하지만 브로드캐스팅이 가능
- 브로드캐스팅(Broadcasting): 서로 다른 shape의 배열에 대해, 어떤 조건을 만족했을 때 연산이 가능해지도록 배열을 자동적으로 변환하는 것. 즉 큰 차원의 배열에 맞게 작은 차원의 배열이 확장.
- 브로드캐스팅 조건:
  1. 두 배열의 차원의 짝이 맞을 때 (차원에 대해 축의 길이가 동일하면) 또는
  2. 두 배열 중 최소한 하나의 배열의 축의 차원의 크기가 1이라면 (1행 또는 1열이라면)  
  - 두 배열은 브로드캐스팅이 가능하며, 브로드캐스팅은 1. 누락된 또는 2. 길이가 1인 차원에 대해 수행된다.

In [ ]:
array3d = np.array([[[0,1],[2,3],[4,5],[6,7]],
                    [[8,9],[10,11],[12,13],[14,15]],
                    [[16,17],[18,19],[20,21],[22,23]]])

In [ ]:
array3d.shape

(3, 4, 2)

In [ ]:
array3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
array2d = np.array([[0,1],[2,3],[4,5],[6,7]])

In [ ]:
array2d.shape

(4, 2)

In [ ]:
array2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
# 1번 조건 만족
array3d + array2d

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]]])

In [ ]:
array8

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array8.shape

(2, 3)

In [ ]:
array10 = np.array([10, 11, 12])
array10

array([10, 11, 12])

In [ ]:
# 2번 조건 만족
array8 + array10

array([[11, 13, 15],
       [14, 16, 18]])

In [ ]:
array8 * array10

array([[10, 22, 36],
       [40, 55, 72]])

In [ ]:
# 스칼라 데이터 타입과도 브로드캐스팅 가능
array8 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
array11=array10.reshape(3,1)
array11

array([[10],
       [11],
       [12]])

In [ ]:
#array10과 array11이 broadcast가능할까?
#-------------------------------------------------

#-------------------------------------------------

array([[20, 21, 22],
       [21, 22, 23],
       [22, 23, 24]])

---

## 3. Array 인덱싱

### 3-1. 기본 인덱싱

#### 1) 1차원 array 인덱싱

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 0번째 요소
arr1[0]

0

In [ ]:
# 3번째 요소
arr1[2]

2

In [ ]:
# 마지막 요소
print(arr1[-1])
print(arr1[len(arr1)-1])

9
9


In [ ]:
arr1[[0,3,5]]

array([0, 3, 5])

#### 2) 슬라이싱

In [ ]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [ ]:
print(arr1[3:])
print(arr1[:-2])
print(arr1[:])

[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8 9]


#### 3) 2차원 array 인덱싱

- 1차원과 달리 다차원 인덱싱에서는 콤마(,)을 기준으로 행과 열을 분리하며
- :을 이용해 각 행, 열 추출

In [ ]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2[2,:] # 행의 인덱스가 2인 값 추출

array([ 9, 10, 11, 12])

In [ ]:
arr2[:,3] # 열의 인덱스가 3인 값 추출

array([ 4,  8, 12])

In [ ]:
arr2[2,3] # 행의 인덱스가 2, 열의 인덱스가 3인 값 추출

12

In [ ]:
#요소 바꾸기
arr2[2,3]=13
arr2

array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 12, 13]])

In [ ]:
arr2[[0,2]] # 2개 이상의 행 추출

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 13]])

In [ ]:
print(arr2[[0,2],-1]) # arr2[행의 인덱스가 0, 열의 인덱스가 -1]과 arr2[행의 인덱스가 2, 열의 인덱스가 -1]
print(arr2[[0,2][-1]]) # 행 단위 인덱싱

[ 4 13]
[ 9 10 11 13]


In [ ]:
# 정수 배열 인덱싱
arr2[[0,2],[0,2]]

array([ 1, 11])

In [ ]:
# 여러 요소 한 번에 바꾸기
arr2[[0,2],[0,2]]=[0,12]
arr2

array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 12, 13]])

In [ ]:
# 1행과 3행의 첫번째, 세번째 원소를 인덱싱해보자
#-----------------------------------------------------

#-----------------------------------------------------

array([[ 0,  3],
       [ 9, 12]])

### 3-2. boolean 인덱싱

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# boolean으로 확인하기
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
# 조건에 맞는 (= 필터링된) 값 불러오기
arr1[arr1 > 5]

array([6, 7, 8, 9])

In [ ]:
# 조건에 맞는 값들의 인덱스 값만 반환
np.where(arr1 > 5)

(array([6, 7, 8, 9]),)

In [ ]:
np.where(arr1 > 5, 'O', 'X')

array(['X', 'X', 'X', 'X', 'X', 'X', 'O', 'O', 'O', 'O'], dtype='<U1')

In [ ]:
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 여기서 짝수는 O 홀수는 X가 뜨게 해보자
#-----------------------------------------------------

#-----------------------------------------------------

array(['O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X'], dtype='<U1')

---

## 4. 자주 쓰이는 Numpy 함수

### 4-1. concatenate - 결합
np.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

가로, 세로 결합에 따라 row, column 개수가 맞아야 결합 가능

In [ ]:
array8

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array9

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
# default axis=0, 행 방향(위아래)으로 결합 (2,3)+(2,3)=(4,3)
array_con1 = np.concatenate((array8, array9))
print(array_con1)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


In [ ]:
# axis=1로 설정 시 열 방향(좌우)로 결합 (2,3)+(2,3)=(2,6)
array_con2 = np.concatenate((array8, array9), axis=1)
print(array_con2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]


In [ ]:
# n차원에서도 concatenate 가능 (2,3,2) + (2,3,2) = (2,3,4)
array_con3=np.concatenate((array5,array5),axis=2)
print(array_con3)

[[[ 1  2  1  2]
  [ 3  4  3  4]
  [ 5  6  5  6]]

 [[ 5  6  5  6]
  [ 7  8  7  8]
  [ 9 10  9 10]]]


### 4-2. split - 분할
np.split(ary, indices_or_sections, axis=0)

같은 크기로만 분할 가능

In [ ]:
# default axis=0, 행 방향(위아래)으로 분할
array = np.split(array_con1,2)
array

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]])]

In [ ]:
# 분할한 결과를 할당
array11, array12 = np.split(array_con1,2)
print(array11)
print(array12)

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


In [ ]:
# axis=1로 설정 시 열 방향(좌우)로 분할
array = np.split(array_con2,2,axis=1)
array

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]])]

### 4-3. sort - 정렬
np.sort(a, axis=-1, kind=None, order=None)

In [ ]:
 array13 = np.array([200,21,922,74,513,1203])

In [ ]:
np.sort(array13) # 오름차순으로 정렬

array([  21,   74,  200,  513,  922, 1203])

In [ ]:
#내림차순은 [::-1] 사용
np.sort(array13)[::-1]

array([1203,  922,  513,  200,   74,   21])

In [ ]:
array12

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
#모든 행에 대해 열 내림차순
array12[:,::-1]

array([[12, 11, 10],
       [15, 14, 13]])

In [ ]:
#모든 열에 대해 행 내림차순
#--------------------------------

#--------------------------------

array([[13, 14, 15],
       [10, 11, 12]])